name: Python Calculator Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        
    - name: Test with pytest and coverage
      run: |
        pytest --cov=calculator --cov-report=xml
        
    - name: Check coverage threshold
      run: |
        COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(float(root.attrib['line-rate']) * 100)")
        echo "Coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 100" | bc -l) )); then
          echo "Coverage is less than 100%"
          exit 1
        else
          echo "Coverage meets requirement of 100%"
        fi
        
    - name: Deploy to prod if coverage is 100%
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b prod
        git push origin prod --force